export const contactList = [
    {
      id: 1,
      name: "Victor",
      wa_id: "33766445477",
      last_text_message: "Hola soy Victor",
      timestamp: "1659683260",
      type: "text",
    },
    {
      id: 2,
      name: "Maria",
      wa_id: "593982441538",
      last_text_message: "Hola soy Maria",
      timestamp: "1659683260",
      type: "text",
    },
    {
        id: 3,
        name: "Marjorie",
        wa_id: "593982441010",
        last_text_message: "Hola soy Marjorie",
        timestamp: "1659683260",
        type: "text",
    },
  ];
  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "Hey Man 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "Hey, What's up?",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Have you subscribed The Indian Dev ?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
  ];